services:
  - type: web
    name: finsight-ai
    env: python
    rootDirectory: AI-Personal-Finance-Tracker
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.5
